[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
optimizer = true
optimizer_runs = 1000
solc_version = "0.8.19"
via_ir = true
gas_reports = ["*"]
gas_limit = 30000000

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[rpc_endpoints]
anvil = "http://localhost:8545"
mainnet = "https://eth-mainnet.alchemyapi.io/v2"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
