[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 1000000
via_ir = true
auto_detect_solc = false

# Sepolia configuration
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
localhost = "http://localhost:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# ZK-specific optimizations
[profile.zk]
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "none"
cbor_metadata = false

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 15
fail_on_revert = false
